/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/civil-servant-examination/': RouteRecordInfo<'/posts/civil-servant-examination/', '/posts/civil-servant-examination', Record<never, never>, Record<never, never>>,
    '/posts/civil-servant-examination/analytical-reasoning': RouteRecordInfo<'/posts/civil-servant-examination/analytical-reasoning', '/posts/civil-servant-examination/analytical-reasoning', Record<never, never>, Record<never, never>>,
    '/posts/civil-servant-examination/data-analysis': RouteRecordInfo<'/posts/civil-servant-examination/data-analysis', '/posts/civil-servant-examination/data-analysis', Record<never, never>, Record<never, never>>,
    '/posts/civil-servant-examination/eassy-writing': RouteRecordInfo<'/posts/civil-servant-examination/eassy-writing', '/posts/civil-servant-examination/eassy-writing', Record<never, never>, Record<never, never>>,
    '/posts/civil-servant-examination/general-knowledge': RouteRecordInfo<'/posts/civil-servant-examination/general-knowledge', '/posts/civil-servant-examination/general-knowledge', Record<never, never>, Record<never, never>>,
    '/posts/civil-servant-examination/political-theory': RouteRecordInfo<'/posts/civil-servant-examination/political-theory', '/posts/civil-servant-examination/political-theory', Record<never, never>, Record<never, never>>,
    '/posts/civil-servant-examination/quantitative-relations': RouteRecordInfo<'/posts/civil-servant-examination/quantitative-relations', '/posts/civil-servant-examination/quantitative-relations', Record<never, never>, Record<never, never>>,
    '/posts/civil-servant-examination/verbal-comprehension-and-expression': RouteRecordInfo<'/posts/civil-servant-examination/verbal-comprehension-and-expression', '/posts/civil-servant-examination/verbal-comprehension-and-expression', Record<never, never>, Record<never, never>>,
    '/posts/datastructure/': RouteRecordInfo<'/posts/datastructure/', '/posts/datastructure', Record<never, never>, Record<never, never>>,
    '/posts/mathematics/': RouteRecordInfo<'/posts/mathematics/', '/posts/mathematics', Record<never, never>, Record<never, never>>,
    '/posts/mathematics/calculus-questions': RouteRecordInfo<'/posts/mathematics/calculus-questions', '/posts/mathematics/calculus-questions', Record<never, never>, Record<never, never>>,
    '/posts/mathematics/formular': RouteRecordInfo<'/posts/mathematics/formular', '/posts/mathematics/formular', Record<never, never>, Record<never, never>>,
    '/posts/my-hello-valaxy': RouteRecordInfo<'/posts/my-hello-valaxy', '/posts/my-hello-valaxy', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
